config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :jobs do
    resources :jobapplications
  end
  resources :questionaires
  get 'jobapplications' => 'jobapplications#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :job_applications
  has_one :questionaire
end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base
  belongs_to :jobhunter
  belongs_to :job

end

app/models/jobhunter.rb
class Jobhunter < ActiveRecord::Base
  has_many :job_applications
end

app/models/questionaire.rb
class Questionaire < ActiveRecord::Base
  belongs_to :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
end

app/controllers/jobapplications_controller.rb
class JobapplicationsController < ApplicationController

  def index
    @applications = JobApplication.all
  end

  def new
    @job = Job.find(params[:job_id])
    jobhunter = Jobhunter.first_or_create
    @job.job_applications.create(jobhunter_id: jobhunter.id)
    redirect_to jobapplications_path
  end
end

app/controllers/jobhunters_controller.rb
class JobhuntersController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new
    @questionaire = Questionaire.new
  end
end

app/controllers/questionaires_controller.rb
class QuestionairesController < ApplicationController
  def new
    @questionaire = Questionaire.new
  end

  def create
    @job = Job.create
    @questionaire = Questionaire.new(questionaire_params, job_id: @job.id)
    @questionaire.job_id = @job.id
    @questionaire.save
    redirect_to '/jobs'
  end

  def questionaire_params
    params.require(:questionaire).permit(:title, :company_name, :size, :tasks)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/jobapplications_helper.rb
module JobapplicationsHelper
end

app/helpers/jobhunters_helper.rb
module JobhuntersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/questionaires_helper.rb
module QuestionairesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobapplications/index.erb
Your application has been received.

app/views/jobs/index.erb
<div class="center">
  <div class="column">
    <h1>Available jobs</h1>
    <% @jobs.each do |job| %>
      <h3><%= job.questionaire.title %></h3> <%= link_to "Apply for #{job.questionaire.title}", new_job_jobapplication_path(job) %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; Jobbit 2015</p>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Jobbit", root_path , class: "btn btn-lg btn-success", id: "logo" %>
    <h1>Jobbit</h1>
    <div class="nav-item">
        <%= link_to 'Sign in', class: "btn btn-default btn-warning" %>
    </div>
    <div class="nav-item">
        <%= link_to 'Sign up', class: "btn btn-default btn-warning" %>
    </div>
    <div class="nav-item">
        <%= link_to "Sign in with Github", class: "btn btn-default btn-warning" %>
    </div> 
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craftathon1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>

  <div class="container">
  <%= yield %>
  
  <%= render 'layouts/footer' %>

</div>

</body>
</html>

app/views/questionaires/new.erb
<%= form_for @questionaire do |f| %>
  <%= f.label 'Job Title:' %>
  <%= f.text_field :title %>
  <%= f.label 'Company Name:' %>
  <%= f.text_field :company_name %>
  <%= f.label 'How big is your existing tech team?' %>
  <%= f.text_field :size %>
  <%= f.label 'How many junior developer jobs are you looking to fill?' %>
  <%= f.text_field :positions %>
  <%= f.label 'What tech does the company use?' %>
  <%= f.text_field :tech %>
  <%= f.label 'What tech will a successful candidate be working with?' %>
  <%= f.text_field :actualtech %>
  <%= f.label 'What will they be doing?' %>
  <%= f.text_field :tasks %>
  <%= f.label 'What results will you want them to deliver?' %>
  <%= f.text_field :results %>
  <%= f.label 'What difference will they make to the company: why will they matter?' %>
  <%= f.text_field :difference %>
  <%= f.label 'What makes someone good at this job?' %>
  <%= f.text_field :ideal %>
  <%= f.label 'What should they expect from your recruitment process?' %>
  <%= f.text_field :recruitment %>
  <%= f.label 'What character traits are you looking for?' %>
  <%= f.text_field :character %>
  <%= f.label 'How will they be on-boarded?' %>
  <%= f.text_field :onboarding %>
  <%= f.label 'What will their training and development look like?' %>
  <%= f.text_field :training %>
  <%= f.label 'How much will you pay?' %>
  <%= f.text_field :pay %>
  <%= f.label 'Where will they work?' %>
  <%= f.text_field :location %>
  <%= f.label 'Would you accept  applications for part-time employment?' %>
  <%= f.text_field :parttime %>
  <%= f.submit 'Create a job' %>
<% end %>

app/views/welcome/index.erb
<div id="main-container" class="container-fluid">
  <div class="row">
    <div id="main-content" class="col-xs-6">
      <h1>Jobseekers</h1>
      <%= link_to 'I am looking for a job', jobs_path, class: "btn btn-primary btn-lg" %>
    </div>
    <div id="main-content" class="col-xs-6">
      <h1>Employers</h1>
      <%= link_to 'I am looking for an employee', new_questionaire_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>